### ISSUE TITLE
Could you please update this?

### ISSUE THREAD

**Issue by willowell** [larskuhtz/ghci-pretty#3]
Hello!

Do you have plans to update this package?

I am having trouble installing this package with GHC 8.10.1 and Cabal 3.2.0.0 – it appears that IPPrint is deprecated in favour of [pretty-show](https://github.com/yav/pretty-show).

**Comment by kindaro** [comment]
This is a fantastic package! My eyes will thank me for making it work. @larskuhtz Please take a look at #4 — possibly you can merge and make a release?

**Comment by larskuhtz** [comment]
I haven't used this package myself since quite a while. But I am glad that it is useful for you. I invited you as a maintainer for the Github package. If you provide me with your Hackage username I can also add you as a package maintainer on Hackage.

**Comment by kindaro** [comment]
Agreeable! My Hackage name is the same as here.

**Comment by kindaro** [comment]
@larskuhtz Ping!

**Comment by larskuhtz** [comment]
done. Thanks for reminding me.
